[package]
name = "mine-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/mc-protocol",
    "crates/mc-client",
    ".",
]

[dependencies]
tokio = "1.47.1"
mc-protocol = { path = "crates/mc-protocol" }
mc-client = { path = "crates/mc-client" }