[package]
name = "mc-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
mc-protocol = { path = "../mc-protocol" }
flate2 = "1.0"
num_enum = "0.7.4"
bytes = "1.6"